name: 'Setup Smithy'
description: 'Installing a version of Smithy CLI and adding it to the PATH'
author: 'Necko Technologies'
inputs:
  version:
    required: false
    description: "Smithy CLI version"
  smithy-build:
    required: false
    description: "path of smithy-build.json file for cache"
runs:
  using: 'node24'
  main: 'dist/setup/index.js'
  post: 'dist/cache/index.js'
  post-if: success()
branding:
  icon: play-circle
  color: red
